#!/usr/bin/php
<?
	if ($argc != 2)
	{
		echo "Incorrect Parameters\n";
		exit(1);
	}
	$s = $argv[1];
	$s = trim($s);
	$str = explode(" ", $s);
	$str = array_filter($str);
	$str = array_values($str);
	if (!is_numeric($str[0]) || !is_numeric($str[2]))
	{
		echo "Syntax Error\n";
		exit(1);
	}
	if($str[1] == "+")
		print_r($str[0] + $str[2]."\n");
	if($str[1] == "-")
		print_r($str[0] - $str[2]."\n");
	if($str[1] == "*")
		print_r($str[0] * $str[2]."\n");
	if($str[1] == "/")
		print_r($str[0] / $str[2]."\n");
	if($str[1] == "%")
		print_r($str[0] % $str[2]."\n");
	 
